# E-Commerce Data Cleaning using Pandas

In [2]:
import pandas as pd
import numpy as np

## Load Dataset

In [3]:
df = pd.read_csv(r'ecommerce_dataset.csv')
df.head()

,Order_ID,Customer_Name,Email,Product_ID,Product_Category,Quantity,Unit_Price,Shipping_Cost,Payment_Method,Delivery_Status,Order_Date
0,ORD-1825,Amit$,NaN,P-100@,Home & Kitchen,5,218.54,NaN,Cash on Delivery,Pending,01/14/2023
1,ORD-1447,Rahul@,test@yahoo.com,P-100@,Electronics,2,477.82,NaN,Credit Card,NaN,30-07-2023
2,ORD-1778,NaN,test@yahoo.com,P-100@,Electronics,one,379.4,NaN,Credit Card,Delivered,06-12-2023
3,ORD-1425,Rahul@,test@yahoo.com,P#200,Electronics,10,319.4,NaN,Paypal,Pending,03/16/2023
4,ORD-2047,Neha!!,wrong@email@.com,P-100@,Electronics,1,120.21,NaN,Net banking,Cancelled,09/20/2023

## Initial Data Understanding

In [4]:
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          1200 non-null   str
 1   Customer_Name     1052 non-null   str
 2   Email             985 non-null    str
 3   Product_ID        938 non-null    str
 4   Product_Category  898 non-null    str
 5   Quantity          970 non-null    str
 6   Unit_Price        1200 non-null   str
 7   Shipping_Cost     0 non-null      float64
 8   Payment_Method    951 non-null    str
 9   Delivery_Status   916 non-null    str
 10  Order_Date        1200 non-null   str
dtypes: float64(1), str(10)
memory usage: 103.3 KB

Order_ID               0
Customer_Name        148
Email                215
Product_ID           262
Product_Category     302
Quantity             230
Unit_Price             0
Shipping_Cost       1200
Payment_Method       249
Delivery_Status      284
Order_Date             0
dtype: int64

In [5]:
for i in df.columns:
    print(i,df[i].sort_values().unique(),"\n",sep="\n")

Order_ID
<StringArray>
[' ORD-1000 ', ' ORD-1020 ', ' ORD-1040 ', ' ORD-1060 ', ' ORD-1080 ',
 ' ORD-1120 ', ' ORD-1160 ', ' ORD-1220 ', ' ORD-1260 ', ' ORD-1280 ',
 ...
   'ORD-2177',   'ORD-2179',   'ORD-2182',   'ORD-2184',   'ORD-2187',
   'ORD-2188',   'ORD-2189',   'ORD-2192',   'ORD-2194',   'ORD-2199']
Length: 754, dtype: str


Customer_Name
<StringArray>
['Amit$', 'Ankit#', 'Neha!!', 'Priya', 'Rahul@', 'Rohit', 'S@nja y', nan]
Length: 8, dtype: str


Email
<StringArray>
['demo@outlook.com', 'test@yahoo.com', 'user@gmail.com', 'wrong@email@.com',
 nan]
Length: 5, dtype: str


Product_ID
<StringArray>
['P 400', 'P#200', 'P-100@', 'P_300', nan]
Length: 5, dtype: str


Product_Category
<StringArray>
['Electronics', 'Fashion', 'Home & Kitchen', nan]
Length: 4, dtype: str


Quantity
<StringArray>
['1', '10', '2', '5', 'one', 'three', 'two', nan]
Length: 8, dtype: str


Unit_Price
<StringArray>
['100.04', '100.42', '100.96', '101.06',  '101.1', '101.68', '102.14',
 '102.23',  '102.6', '102.68',
 ...
  '96.13',  '96.41',  '96.85',  '97.97',  '98.14',  '98.23',  '98.55',
  '99.52',  '99.71',  '99.78']
Length: 1190, dtype: str


Shipping_Cost
[nan]


Payment_Method
<StringArray>
['Cash on Delivery', 'Credit Card', 'Net banking', 'Paypal', nan]
Length: 5, dtype: str


Delivery_Status
<StringArray>
['Cancelled', 'Delivered', 'Pending', nan]
Length: 4, dtype: str


Order_Date
<StringArray>
['01-01-2023', '01-01-2024', '01-02-2023', '01-03-2023', '01-04-2023',
 '01-05-2023', '01-06-2023', '01-07-2023', '01-08-2023', '01-09-2023',
 ...
 '30-09-2023', '30-10-2023', '30-11-2023', '31-01-2023', '31-03-2023',
 '31-05-2023', '31-07-2023', '31-08-2023', '31-10-2023', '31-12-2023']
Length: 487, dtype: str

## Basic Cleaning

In [6]:
df['Customer_Name'] = df['Customer_Name'].fillna('Guest')
df = df.drop_duplicates()
df['Unit_Price'] = df['Unit_Price'].astype(str).str.replace(r'[^0-9.]', '', regex=True).astype(float)
df.Unit_Price

0       218.54
1       477.82
2       379.40
3       319.40
4       120.21
         ...
1195    442.19
1196    488.07
1197    486.00
1198    387.34
1199    108.54
Name: Unit_Price, Length: 1200, dtype: float64

## Quantity Cleaning

In [7]:
word_to_num = {'one':1,'two':2,'three':3}
df['Quantity'] = df['Quantity'].replace(word_to_num)
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')
df = df[df['Quantity'] > 0]

In [8]:
df['Product_Category'] = df['Product_Category'].replace({
    'electronic': 'electronics',
    'elec': 'electronics'
})

## Date Standardization

In [9]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')

## Advanced Cleaning

In [10]:
df['Order_ID'] = df['Order_ID'].str.replace(r'[^a-zA-Z0-9]', '', regex=True)

In [11]:
df.dtypes

Order_ID                       str
Customer_Name                  str
Email                          str
Product_ID                     str
Product_Category               str
Quantity                   float64
Unit_Price                 float64
Shipping_Cost              float64
Payment_Method                 str
Delivery_Status                str
Order_Date          datetime64[us]
dtype: object

## Feature Engineering

In [12]:
df['Total_Amount'] = df['Unit_Price'] * df['Quantity']
df['Order_Year'] = df['Order_Date'].dt.year

## Regex-based Cleaning

In [13]:
df['Customer_Name'] = df['Customer_Name'].str.replace(r'[^A-Za-z ]','', regex=True)

## Final Cleaned Data

In [14]:
df.reset_index(drop=True, inplace=True)
df.head()

,Order_ID,Customer_Name,Email,Product_ID,Product_Category,Quantity,Unit_Price,Shipping_Cost,Payment_Method,Delivery_Status,Order_Date,Total_Amount,Order_Year
0,ORD1825,Amit,NaN,P-100@,Home & Kitchen,5.0,218.54,NaN,Cash on Delivery,Pending,2023-01-14,1092.70,2023.0
1,ORD1447,Rahul,test@yahoo.com,P-100@,Electronics,2.0,477.82,NaN,Credit Card,NaN,NaT,955.64,NaN
2,ORD1778,Guest,test@yahoo.com,P-100@,Electronics,1.0,379.40,NaN,Credit Card,Delivered,NaT,379.40,NaN
3,ORD1425,Rahul,test@yahoo.com,P#200,Electronics,10.0,319.40,NaN,Paypal,Pending,2023-03-16,3194.00,2023.0
4,ORD2047,Neha,wrong@email@.com,P-100@,Electronics,1.0,120.21,NaN,Net banking,Cancelled,2023-09-20,120.21,2023.0

In [15]:
df[["Unit_Price","Quantity"]] = df[["Unit_Price","Quantity"]].fillna(df[["Unit_Price","Quantity"]].mean())

In [16]:
def new_col(data):
    if data<=150:
        return "Low Price of Product"
    elif data>150 and data<=370:
        return "Medium Price  Of Product"
    else:
        return "High Cost Of Product"


df["Price_Category"] = df["Unit_Price"].apply(new_col)

In [17]:
df.head()

,Order_ID,Customer_Name,Email,Product_ID,Product_Category,Quantity,Unit_Price,Shipping_Cost,Payment_Method,Delivery_Status,Order_Date,Total_Amount,Order_Year,Price_Category
0,ORD1825,Amit,NaN,P-100@,Home & Kitchen,5.0,218.54,NaN,Cash on Delivery,Pending,2023-01-14,1092.70,2023.0,Medium Price Of Product
1,ORD1447,Rahul,test@yahoo.com,P-100@,Electronics,2.0,477.82,NaN,Credit Card,NaN,NaT,955.64,NaN,High Cost Of Product
2,ORD1778,Guest,test@yahoo.com,P-100@,Electronics,1.0,379.40,NaN,Credit Card,Delivered,NaT,379.40,NaN,High Cost Of Product
3,ORD1425,Rahul,test@yahoo.com,P#200,Electronics,10.0,319.40,NaN,Paypal,Pending,2023-03-16,3194.00,2023.0,Medium Price Of Product
4,ORD2047,Neha,wrong@email@.com,P-100@,Electronics,1.0,120.21,NaN,Net banking,Cancelled,2023-09-20,120.21,2023.0,Low Price of Product